packages:
  - packages/*
  - apps/*

catalog:
  '@tailwindcss/vite': ^4.1.12
  '@types/node': ^24.3.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.0.1
  '@vue/tsconfig': ^0.7.0
  eslint: ^9.33.0
  lucide-vue-next: ~0.540.0
  pinia: ^3.0.3
  reka-ui: ^2.4.1
  tailwindcss: ^4.1.12
  tsdown: ^0.14.1
  turbo: ^2.5.6
  typescript: ^5.9.2
  vite: ^7.1.3
  vite-plugin-dts: ^4.0.1
  vitest: ^3.2.4
  vue: ^3.5.19
  vue-router: ^4.5.1
  vue-tsc: ^3.0.6
